In [ ]:
import os

import pandas as pd

file_name = f"data/data_small/TG_STAID000001.txt"

df = pd.read_csv(
    file_name,
    skiprows=20,
    parse_dates=["    DATE"],
    date_format="%Y%m%d",
)
df_filtered = df[df[" Q_TG"] == 0]
len(df_filtered[df_filtered["    DATE"].dt.year == 1860])

     STAID   SOUID       DATE     TG   Q_TG
0        1   35381 1860-01-01     21      0
1        1   35381 1860-01-02     46      0
2        1   35381 1860-01-03     31      0
3        1   35381 1860-01-04     37      0
4        1   35381 1860-01-05     31      0
..     ...     ...        ...    ...    ...
361      1   35381 1860-12-27   -100      0
362      1   35381 1860-12-28    -98      0
363      1   35381 1860-12-29    -71      0
364      1   35381 1860-12-30    -35      0
365      1   35381 1860-12-31   -121      0

[363 rows x 5 columns]

In [ ]:
1860-01-01

   col1  col2  col3
1     2     4     5